### PR TITLE
Updating to use pure go xz lib

### PR DESCRIPTION
**Pull request by jasonmoo**
Hi.  Thanks for the great lib.  I switched to a pure go xz lib for easier cross-compillation.  It passes tests and works great for me.  Feel free to merge or discard if you're happier with the existing lib.

Thanks!
Jason

### CODE REVIEW

**Comment by akhenakh** [comment]
Hey thanks for the PR, unfortunately pure xz is terribly slow, look at this previous PR: https://github.com/akhenakh/gozim/pull/32

Can you please check the performance and see if it's better now ?

**Comment by jasonmoo** [comment]
Hi Cool totally missed that old PR.  You are correct the pure go implementation is ~2.5x slower.  

I need the cross-compilation ability so I will be keeping the change, but I understand if you want to prioritize performance in your lib.  It's a shame the perf difference is so significant.

I added a benchmark that clears the LRU and tested both libs.  The memory increase is harder to measure due to cgo obfuscating what the underlying c code is allocing.  
Benchcmp for 10 runs on each lib.  
```
jason@mba ~/go/src/github.com/jasonmoo/gozim master: benchcmp -best cgo.txt go.txt 
benchmark                   old ns/op     new ns/op     delta
BenchmarkArticleBytes-4     29053948      78114929      +168.86%

benchmark                   old MB/s     new MB/s     speedup
BenchmarkArticleBytes-4     2.72         1.01         0.37x

benchmark                   old allocs     new allocs     delta
BenchmarkArticleBytes-4     126            215620         +171026.98%

benchmark                   old bytes     new bytes     delta
BenchmarkArticleBytes-4     6439808       75718960      +1075.80%
```

**Comment by akhenakh** [comment]
2.5x diff would be ok, but I know some ppl, myself included,are using it on giant gozim like wikipedia, where the performance hit would be too high.

Is the API for pure xz exactly the same, maybe we could incorporate your changes with a build flags ?

**Comment by jasonmoo** [comment]
I added the change behind a build tag.  This defaults to the pure go lib when cross-compiling but the cgo lib when compiling natively.

**Comment by akhenakh** [comment]
awesome ! thank you

**Pull request merged**
